### ISSUE TITLE
vite-plugin-vconsole 该插件是不是有问题？

### ISSUE THREAD

**Issue by chenguzhen87** [vadxq/vite-plugin-vconsole#1]
在页面上看不到vsconsole按纽

**Comment by vadxq** [comment]
你好，可以贴一下vite.config的配置嘛？

**Comment by chenguzhen87** [comment]
我看你的，模板项目也没看到vsconsole按纽，都安装了的vconsole和vite-plugin-vconsole，
https://github.com/parajs/vue3-mobile-template/blob/master/vite.config.ts

**Comment by vadxq** [comment]
我跑了一下您的项目，dev环境下是显示的。
![image](https://user-images.githubusercontent.com/18227775/146593282-6d49cf7b-5845-4753-ae2e-8f08c56fd9f6.png)

想更具体的问一下：是在build后的产物没有出现vconsole吗？我的模版里默认情况下生产环境不打包进去的。打包测试环境或者是dev环境预览这些会打进去的。多环境可以参考这个配置https://github.com/vadxq/vite-vue-prod-template/blob/405e6dc22ca30b9a969fd352b307593241b760b0/vite.config.ts#L54

**Comment by vadxq** [comment]
@chenguzhen87 您好，请问您是否是在windows下使用出现的问题？目前新发布了v1.1.1包，解决了windows下加载vconsle失败的情况。您是否需要再试试看？

**Comment by chenguzhen87** [comment]
是的，可以了
