### ISSUE TITLE
参数设计的让人很费解

### ISSUE THREAD

**Issue by liuweiGL** [vadxq/vite-plugin-vconsole#10]
`enabled` 跟 `localEnabled` 看了源码才知道分别是生产环境跟开发环境是否启用的配置，个人建议可以把这两个配置项合并成`enableMode` 字段以便跟 vite 对齐。

或者干脆取消，让用户自己在 vite 配置中根据 `mode` 判断是否加载插件。

内部判断太隐晦了：
https://github.com/vadxq/vite-plugin-vconsole/blob/6f85d19fc36f1137f73ac2a3073a43a1ddc3f88d/src/index.ts#L40

**Comment by vadxq** [comment]
好的！感谢建议，会在下一个版本跟vite对齐。这个配置当初比较早期，设计不够友好。

**Comment by vadxq** [comment]
目前在2.x版本已经删除了localEnabled参数，只保留enabled参数，由用户在外部控制，可以体验提提建议哟～https://www.npmjs.com/package/vite-plugin-vconsole/v/2.0.0-beta.0
