### ISSUE TITLE
vite 3.0能用吗？ 

### ISSUE THREAD

**Issue by 897387171** [vadxq/vite-plugin-vconsole#11]
最近在用vite3.0 引入了貌似没用

**Comment by vadxq** [comment]
可以使用的，需要配置开启。我司项目是vite3+react18，使用没问题。可以看看你的配置选项吗

**Comment by 897387171** [comment]
在vite.config.ts中按你们那个配置项加入了无法起作用，现在是是main.ts直接new了Vconsole是可以使用了，但不是使用的这个插件。是vue3+vant3+ts的一个项目

**Comment by vadxq** [comment]
需要同时安装两个包
`
vite-plugin-vconsole
vconsole
`
https://github.com/vadxq/vite-react-starter/blob/main/package.json#L77

然后配置可以参考这个
https://github.com/vadxq/vite-react-starter/blob/main/vite.config.ts#L44

可以参考这个项目，vite3.0:https://github.com/vadxq/vite-react-starter

试试上面这样有效果吗？

**Comment by 897387171** [comment]
可以了  感谢，之前应该是我地址完全按照readme文档的`src/main.ts`不对，应该是`./src/main.ts`
