### ISSUE TITLE
如何判断页面userAgent来选择是否加载vconsole

### ISSUE THREAD

**Issue by hi500** [vadxq/vite-plugin-vconsole#12]
在pc电脑端调试的时候，不希望有vconsole，因为vconsole会拦截console的log信息，不便于定位代码。
但是vite的配置文件中，启动的时候无法拿到浏览器的userAgent，这个问题怎么解决，只能是页面打开的时候再去判断是否初始化vconsole了吗

**Comment by vadxq** [comment]
这个似乎目前暂无法支持，后续参数优化的新版本可以考虑加上这个需求

**Comment by vadxq** [comment]
可自定义规则来判断页面userAgent正式版发布啦，欢迎体验：[vite-plugin-vconsole v2.0.0](https://www.npmjs.com/package/vite-plugin-vconsole/v/2.0.0)
