### ISSUE TITLE
如何自定义vconsole插件

### ISSUE THREAD

**Issue by chaserstrong** [vadxq/vite-plugin-vconsole#15]
似乎被封死了？看仓库代码好像也不完整。 
要怎么自定义vconsole的插件呢，或者获取vconsole自带面板的一些方法事件什么的？

**Comment by vadxq** [comment]
可自定义插件正式版发布啦，欢迎体验：[vite-plugin-vconsole v2.0.0](https://www.npmjs.com/package/vite-plugin-vconsole/v/2.0.0)
