### ISSUE TITLE
设置不生效报错页面空白

### ISSUE THREAD

**Issue by leishihong** [vadxq/vite-plugin-vconsole#4]
Uncaught ReferenceError: Cannot access 'VConsole' before initialization
    at main.ts:16:18

**Comment by vadxq** [comment]
@leishihong  你好，想问一下可以贴一下关于vconsole的vite配置，vite版本，插件版本和vconsole版本嘛

**Comment by leishihong** [comment]
@vadxq 

vite.config.ts 配置

viteVConsole({
				entry: pathResolve('src/main.ts').replace(/\\/g, '/'), 
				localEnabled: command === 'serve', 
        		enabled: command !== 'serve' || mode === 'test', 
				config: {
					maxLogNumber: 1000,
					theme: "dark",
				},
			}),


"vconsole": "^3.12.0",

 "vite": "^2.7.2",

 "vite-plugin-vconsole": "^1.1.1",

没有在main.ts 中引入vconsole 引入以后就报错了

**Comment by leishihong** [comment]
vite.config.ts 配置

viteVConsole({
entry: pathResolve('src/main.ts').replace(/\/g, '/'),
localEnabled: command === 'serve',
enabled: command !== 'serve' || mode === 'test',
config: {
maxLogNumber: 1000,
theme: "dark",
},
}),

"vconsole": "^3.12.0",

"vite": "^2.7.2",

"vite-plugin-vconsole": "^1.1.1",

没有在main.ts 中引入vconsole 引入以后就报错了



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vadxq/vite-plugin-vconsole"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月25日(星期五) 上午10:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vadxq/vite-plugin-vconsole] 设置不生效报错页面空白 (Issue #4)





 
@leishihong  你好，想问一下可以贴一下关于vconsole的vite配置，vite版本，插件版本和vconsole版本嘛
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by vadxq** [comment]
@leishihong 
方便贴一下main.ts中关于vconsole处理的代码嘛？
另：在main.ts可以不需要引入vconsole，配置里配置开启就可以看到vconsole了。entry配置的.replace(/\/g, '/')这行可以不用处理了，V1.1.1+处理过这个window问题。

**Comment by leishihong** [comment]
我没有引入



「您的联系方式是啥」？？？？？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vadxq/vite-plugin-vconsole"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月25日(星期五) 中午12:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vadxq/vite-plugin-vconsole] 设置不生效报错页面空白 (Issue #4)





 
@leishihong
 方便贴一下main.ts中关于vconsole处理的代码嘛？
 另：在main.ts可以不需要引入vconsole，配置里配置开启就可以看到vconsole了。entry配置的.replace(//g, '/')这行可以不用处理了，V1.1.1+处理过这个window问题。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by vadxq** [comment]
@leishihong 有最小可复现的代码嘛？方便在CodeSandbox/CodePen/jsFiddle等平台配一个看看嘛？
联系邮箱dongxianlin@vadxq.com
