### ISSUE TITLE
build开启sourcemap，会有很多警告

### ISSUE THREAD

**Issue by jane900618** [vadxq/vite-plugin-vconsole#5]
警告如下：
Sourcemap is likely to be incorrect: a plugin (vite:vconsole) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help

**Comment by vadxq** [comment]
已关注，正在处理中

**Comment by vadxq** [comment]
@jane900618 已修复，可以更新版本v1.2.2
https://github.com/vadxq/vite-plugin-vconsole/tree/v1.2.2
