### ISSUE TITLE
error: [plugin externalize-deps] Failed 

### ISSUE THREAD

**Issue by xiaobo1215** [vadxq/vite-plugin-vconsole#8]
✘ [ERROR] [plugin externalize-deps] Failed to resolve entry for package "vite-plugin-vconsole". The package may have incorrect main/module/exports specified in its package.json.

VITE v3.1.8  
node v14.19.0

**Comment by xiaobo1215** [comment]
![image](https://user-images.githubusercontent.com/20086016/196905553-c3af4f65-542e-48d2-ab68-aa766b7444e3.png)

**Comment by xiaobo1215** [comment]
![image](https://user-images.githubusercontent.com/20086016/196905846-89e89a9c-d4d2-4afc-aa34-92fdf9c090b6.png)

**Comment by vadxq** [comment]
Now, you can download [v1.3.1](https://www.npmjs.com/package/vite-plugin-vconsole/v/1.3.1) to solve it. Thank you very much for your support.
